apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-operator
  namespace: vault-restricted
  labels:
    control-plane: vault-operator
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/instance: vault-operator
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: vault-operator
    app.kubernetes.io/part-of: vault-operator
spec:
  selector:
    matchLabels:
      control-plane: vault-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: vault-operator
    spec:
      # Pod-level security context for Pod Security Standards compliance
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /usr/local/bin/vault-operator
        image: controller:latest
        name: manager
        # Container security context for Pod Security Standards compliance
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          capabilities:
            drop:
              - "ALL"
          seccompProfile:
            type: RuntimeDefault
        # Add volume mounts for read-only root filesystem
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /.cache
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      # Add volumes for read-only root filesystem
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      serviceAccountName: vault-operator
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-operator
  namespace: vault-restricted
  labels:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/instance: vault-operator
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: vault-operator
    app.kubernetes.io/part-of: vault-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-operator-leader-election
  namespace: vault-restricted
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-operator-leader-election
  namespace: vault-restricted
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-operator-leader-election
subjects:
- kind: ServiceAccount
  name: vault-operator
  namespace: vault-restricted
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-operator-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.banzaicloud.com
  resources:
  - vaults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.banzaicloud.com
  resources:
  - vaults/finalizers
  verbs:
  - update
- apiGroups:
  - vault.banzaicloud.com
  resources:
  - vaults/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-operator-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-operator-manager
subjects:
- kind: ServiceAccount
  name: vault-operator
  namespace: vault-restricted
