run:
  timeout: 10m

issues:
  exclude-dirs:
    - pkg/apis

    # TODO: fixme
    - pkg/controller

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/bank-vaults/vault-operator)
  goimports:
    local-prefixes: github.com/bank-vaults/vault-operator
  misspell:
    locale: US
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  revive:
    confidence: 0

linters:
  enable:
    - bodyclose
    - errcheck
    - gci
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - unconvert
    - unparam
    - unused
    - whitespace
