// Copyright © 2019 Banzai Cloud
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	vaultv1alpha1 "github.com/bank-vaults/vault-operator/pkg/apis/vault/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VaultLister helps list Vaults.
// All objects returned here must be treated as read-only.
type VaultLister interface {
	// List lists all Vaults in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vaultv1alpha1.Vault, err error)
	// Vaults returns an object that can list and get Vaults.
	Vaults(namespace string) VaultNamespaceLister
	VaultListerExpansion
}

// vaultLister implements the VaultLister interface.
type vaultLister struct {
	listers.ResourceIndexer[*vaultv1alpha1.Vault]
}

// NewVaultLister returns a new VaultLister.
func NewVaultLister(indexer cache.Indexer) VaultLister {
	return &vaultLister{listers.New[*vaultv1alpha1.Vault](indexer, vaultv1alpha1.Resource("vault"))}
}

// Vaults returns an object that can list and get Vaults.
func (s *vaultLister) Vaults(namespace string) VaultNamespaceLister {
	return vaultNamespaceLister{listers.NewNamespaced[*vaultv1alpha1.Vault](s.ResourceIndexer, namespace)}
}

// VaultNamespaceLister helps list and get Vaults.
// All objects returned here must be treated as read-only.
type VaultNamespaceLister interface {
	// List lists all Vaults in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*vaultv1alpha1.Vault, err error)
	// Get retrieves the Vault from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*vaultv1alpha1.Vault, error)
	VaultNamespaceListerExpansion
}

// vaultNamespaceLister implements the VaultNamespaceLister
// interface.
type vaultNamespaceLister struct {
	listers.ResourceIndexer[*vaultv1alpha1.Vault]
}
