blank_issues_enabled: true
contact_links:
  - name: 📖 Documentation enhancement
    url: https://github.com/bank-vaults/bank-vaults.dev/issues
    about: Suggest an improvement to the documentation

  - name: ❓ Ask a question
    url: https://github.com/bank-vaults/vault-operator/discussions/new?category=q-a
    about: Ask and discuss questions with other Bank-Vaults community members

  - name: 📚 Documentation
    url: https://bank-vaults.dev/docs/operator
    about: Check the documentation for help

  - name: 💬 Slack channel
    url: https://cloud-native.slack.com/archives/C078PHYK38W/
    about: Please ask and answer questions here
