// Copyright © 2023 Bank-Vaults
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// AWSUnsealConfigApplyConfiguration represents an declarative configuration of the AWSUnsealConfig type for use
// with apply.
type AWSUnsealConfigApplyConfiguration struct {
	KMSKeyID  *string `json:"kmsKeyId,omitempty"`
	KMSRegion *string `json:"kmsRegion,omitempty"`
	S3Bucket  *string `json:"s3Bucket,omitempty"`
	S3Prefix  *string `json:"s3Prefix,omitempty"`
	S3Region  *string `json:"s3Region,omitempty"`
	S3SSE     *string `json:"s3SSE,omitempty"`
}

// AWSUnsealConfigApplyConfiguration constructs an declarative configuration of the AWSUnsealConfig type for use with
// apply.
func AWSUnsealConfig() *AWSUnsealConfigApplyConfiguration {
	return &AWSUnsealConfigApplyConfiguration{}
}

// WithKMSKeyID sets the KMSKeyID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KMSKeyID field is set to the value of the last call.
func (b *AWSUnsealConfigApplyConfiguration) WithKMSKeyID(value string) *AWSUnsealConfigApplyConfiguration {
	b.KMSKeyID = &value
	return b
}

// WithKMSRegion sets the KMSRegion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KMSRegion field is set to the value of the last call.
func (b *AWSUnsealConfigApplyConfiguration) WithKMSRegion(value string) *AWSUnsealConfigApplyConfiguration {
	b.KMSRegion = &value
	return b
}

// WithS3Bucket sets the S3Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the S3Bucket field is set to the value of the last call.
func (b *AWSUnsealConfigApplyConfiguration) WithS3Bucket(value string) *AWSUnsealConfigApplyConfiguration {
	b.S3Bucket = &value
	return b
}

// WithS3Prefix sets the S3Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the S3Prefix field is set to the value of the last call.
func (b *AWSUnsealConfigApplyConfiguration) WithS3Prefix(value string) *AWSUnsealConfigApplyConfiguration {
	b.S3Prefix = &value
	return b
}

// WithS3Region sets the S3Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the S3Region field is set to the value of the last call.
func (b *AWSUnsealConfigApplyConfiguration) WithS3Region(value string) *AWSUnsealConfigApplyConfiguration {
	b.S3Region = &value
	return b
}

// WithS3SSE sets the S3SSE field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the S3SSE field is set to the value of the last call.
func (b *AWSUnsealConfigApplyConfiguration) WithS3SSE(value string) *AWSUnsealConfigApplyConfiguration {
	b.S3SSE = &value
	return b
}
