apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault-cluster"
  namespace: vault-restricted
  labels:
    app.kubernetes.io/name: vault-cluster
    vault_cr: vault-cluster
spec:
  size: 5
  image: hashicorp/vault:1.15.6
  
  # Service configuration
  serviceType: ClusterIP
  serviceAccount: vault
  
  # Environment variables for Pod Security compliance
  vaultEnvsConfig:
    - name: SKIP_CHOWN
      value: "true"
    - name: SKIP_SETCAP
      value: "true"
    - name: VAULT_DISABLE_MLOCK
      value: "true"
  
  # Global security context (base for all pods)
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    fsGroup: 65532
    seccompProfile:
      type: RuntimeDefault

  # Vault StatefulSet pods specific security context
  vaultPodSpec:
    securityContext:
      # Override defaults if needed - inherits from global securityContext
      # Example: different user for vault pods
      # runAsUser: 1000
      # runAsGroup: 1000
      # fsGroup: 1000

  # Vault Configurer deployment specific security context
  vaultConfigurerPodSpec:
    securityContext:
      # Override defaults if needed - inherits from global securityContext
      # Example: different configuration for configurer
      # runAsUser: 2000
      # runAsGroup: 2000

  # Vault container specific security context
  vaultContainerSpec:
    name: vault
    securityContext:
      # Override defaults if needed - gets Pod Security compliant defaults
      # Example: add specific capabilities or constraints
      # readOnlyRootFilesystem: true

  # Persistent storage for each node
  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn

  volumeMounts:
    - name: vault-raft
      mountPath: /vault/file

  # Vault configuration for HA with Raft  
  config:
    storage:
      raft:
        path: "/vault/file"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_disable: true
    api_addr: "http://vault-cluster:8200" 
    cluster_addr: "http://${.Env.POD_NAME}:8201"
    ui: true
    disable_mlock: true

  # Unsealing configuration
  unsealConfig:
    options:
      preFlightChecks: true
      storeRootToken: true
      secretShares: 5
      secretThreshold: 3
    kubernetes:
      secretNamespace: vault-restricted

  # Disable statsd to reduce complexity
  statsdDisabled: true

  # Resource requirements
  resources:
    vault:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m

  # External configuration for initial setup
  externalConfig:
    policies:
      - name: allow_secrets
        rules: |
          path "secret/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
    auth:
      - type: kubernetes
        roles:
          - name: default
            bound_service_account_names: ["default"]
            bound_service_account_namespaces: ["vault-restricted"]
            policies: ["allow_secrets"]
            ttl: 1h
    secrets:
      - path: secret
        type: kv
        description: General secrets storage
        options:
          version: 2