// Copyright © 2023 Bank-Vaults
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GoogleUnsealConfigApplyConfiguration represents an declarative configuration of the GoogleUnsealConfig type for use
// with apply.
type GoogleUnsealConfigApplyConfiguration struct {
	KMSKeyRing    *string `json:"kmsKeyRing,omitempty"`
	KMSCryptoKey  *string `json:"kmsCryptoKey,omitempty"`
	KMSLocation   *string `json:"kmsLocation,omitempty"`
	KMSProject    *string `json:"kmsProject,omitempty"`
	StorageBucket *string `json:"storageBucket,omitempty"`
}

// GoogleUnsealConfigApplyConfiguration constructs an declarative configuration of the GoogleUnsealConfig type for use with
// apply.
func GoogleUnsealConfig() *GoogleUnsealConfigApplyConfiguration {
	return &GoogleUnsealConfigApplyConfiguration{}
}

// WithKMSKeyRing sets the KMSKeyRing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KMSKeyRing field is set to the value of the last call.
func (b *GoogleUnsealConfigApplyConfiguration) WithKMSKeyRing(value string) *GoogleUnsealConfigApplyConfiguration {
	b.KMSKeyRing = &value
	return b
}

// WithKMSCryptoKey sets the KMSCryptoKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KMSCryptoKey field is set to the value of the last call.
func (b *GoogleUnsealConfigApplyConfiguration) WithKMSCryptoKey(value string) *GoogleUnsealConfigApplyConfiguration {
	b.KMSCryptoKey = &value
	return b
}

// WithKMSLocation sets the KMSLocation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KMSLocation field is set to the value of the last call.
func (b *GoogleUnsealConfigApplyConfiguration) WithKMSLocation(value string) *GoogleUnsealConfigApplyConfiguration {
	b.KMSLocation = &value
	return b
}

// WithKMSProject sets the KMSProject field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KMSProject field is set to the value of the last call.
func (b *GoogleUnsealConfigApplyConfiguration) WithKMSProject(value string) *GoogleUnsealConfigApplyConfiguration {
	b.KMSProject = &value
	return b
}

// WithStorageBucket sets the StorageBucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageBucket field is set to the value of the last call.
func (b *GoogleUnsealConfigApplyConfiguration) WithStorageBucket(value string) *GoogleUnsealConfigApplyConfiguration {
	b.StorageBucket = &value
	return b
}
