// Copyright © 2023 Bank-Vaults
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// UnsealConfigApplyConfiguration represents an declarative configuration of the UnsealConfig type for use
// with apply.
type UnsealConfigApplyConfiguration struct {
	Options    *UnsealOptionsApplyConfiguration          `json:"options,omitempty"`
	Kubernetes *KubernetesUnsealConfigApplyConfiguration `json:"kubernetes,omitempty"`
	Google     *GoogleUnsealConfigApplyConfiguration     `json:"google,omitempty"`
	Alibaba    *AlibabaUnsealConfigApplyConfiguration    `json:"alibaba,omitempty"`
	Azure      *AzureUnsealConfigApplyConfiguration      `json:"azure,omitempty"`
	AWS        *AWSUnsealConfigApplyConfiguration        `json:"aws,omitempty"`
	Vault      *VaultUnsealConfigApplyConfiguration      `json:"vault,omitempty"`
	HSM        *HSMUnsealConfigApplyConfiguration        `json:"hsm,omitempty"`
}

// UnsealConfigApplyConfiguration constructs an declarative configuration of the UnsealConfig type for use with
// apply.
func UnsealConfig() *UnsealConfigApplyConfiguration {
	return &UnsealConfigApplyConfiguration{}
}

// WithOptions sets the Options field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Options field is set to the value of the last call.
func (b *UnsealConfigApplyConfiguration) WithOptions(value *UnsealOptionsApplyConfiguration) *UnsealConfigApplyConfiguration {
	b.Options = value
	return b
}

// WithKubernetes sets the Kubernetes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kubernetes field is set to the value of the last call.
func (b *UnsealConfigApplyConfiguration) WithKubernetes(value *KubernetesUnsealConfigApplyConfiguration) *UnsealConfigApplyConfiguration {
	b.Kubernetes = value
	return b
}

// WithGoogle sets the Google field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Google field is set to the value of the last call.
func (b *UnsealConfigApplyConfiguration) WithGoogle(value *GoogleUnsealConfigApplyConfiguration) *UnsealConfigApplyConfiguration {
	b.Google = value
	return b
}

// WithAlibaba sets the Alibaba field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Alibaba field is set to the value of the last call.
func (b *UnsealConfigApplyConfiguration) WithAlibaba(value *AlibabaUnsealConfigApplyConfiguration) *UnsealConfigApplyConfiguration {
	b.Alibaba = value
	return b
}

// WithAzure sets the Azure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Azure field is set to the value of the last call.
func (b *UnsealConfigApplyConfiguration) WithAzure(value *AzureUnsealConfigApplyConfiguration) *UnsealConfigApplyConfiguration {
	b.Azure = value
	return b
}

// WithAWS sets the AWS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AWS field is set to the value of the last call.
func (b *UnsealConfigApplyConfiguration) WithAWS(value *AWSUnsealConfigApplyConfiguration) *UnsealConfigApplyConfiguration {
	b.AWS = value
	return b
}

// WithVault sets the Vault field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vault field is set to the value of the last call.
func (b *UnsealConfigApplyConfiguration) WithVault(value *VaultUnsealConfigApplyConfiguration) *UnsealConfigApplyConfiguration {
	b.Vault = value
	return b
}

// WithHSM sets the HSM field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HSM field is set to the value of the last call.
func (b *UnsealConfigApplyConfiguration) WithHSM(value *HSMUnsealConfigApplyConfiguration) *UnsealConfigApplyConfiguration {
	b.HSM = value
	return b
}
