// Copyright © 2019 Banzai Cloud
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	vaultv1alpha1 "github.com/bank-vaults/vault-operator/pkg/apis/vault/v1alpha1"
	scheme "github.com/bank-vaults/vault-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VaultsGetter has a method to return a VaultInterface.
// A group's client should implement this interface.
type VaultsGetter interface {
	Vaults(namespace string) VaultInterface
}

// VaultInterface has methods to work with Vault resources.
type VaultInterface interface {
	Create(ctx context.Context, vault *vaultv1alpha1.Vault, opts v1.CreateOptions) (*vaultv1alpha1.Vault, error)
	Update(ctx context.Context, vault *vaultv1alpha1.Vault, opts v1.UpdateOptions) (*vaultv1alpha1.Vault, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*vaultv1alpha1.Vault, error)
	List(ctx context.Context, opts v1.ListOptions) (*vaultv1alpha1.VaultList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *vaultv1alpha1.Vault, err error)
	VaultExpansion
}

// vaults implements VaultInterface
type vaults struct {
	*gentype.ClientWithList[*vaultv1alpha1.Vault, *vaultv1alpha1.VaultList]
}

// newVaults returns a Vaults
func newVaults(c *VaultV1alpha1Client, namespace string) *vaults {
	return &vaults{
		gentype.NewClientWithList[*vaultv1alpha1.Vault, *vaultv1alpha1.VaultList](
			"vaults",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *vaultv1alpha1.Vault { return &vaultv1alpha1.Vault{} },
			func() *vaultv1alpha1.VaultList { return &vaultv1alpha1.VaultList{} },
		),
	}
}
