// Copyright © 2023 Bank-Vaults
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha2 "github.com/bank-vaults/vault-operator/v2/pkg/apis/vault/v1alpha2"
	vaultv1alpha2 "github.com/bank-vaults/vault-operator/v2/pkg/client/applyconfiguration/vault/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVaults implements VaultInterface
type FakeVaults struct {
	Fake *FakeVaultV1alpha2
	ns   string
}

var vaultsResource = v1alpha2.SchemeGroupVersion.WithResource("vaults")

var vaultsKind = v1alpha2.SchemeGroupVersion.WithKind("Vault")

// Get takes name of the vault, and returns the corresponding vault object, and an error if there is any.
func (c *FakeVaults) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.Vault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vaultsResource, c.ns, name), &v1alpha2.Vault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Vault), err
}

// List takes label and field selectors, and returns the list of Vaults that match those selectors.
func (c *FakeVaults) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.VaultList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vaultsResource, vaultsKind, c.ns, opts), &v1alpha2.VaultList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.VaultList{ListMeta: obj.(*v1alpha2.VaultList).ListMeta}
	for _, item := range obj.(*v1alpha2.VaultList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vaults.
func (c *FakeVaults) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vaultsResource, c.ns, opts))

}

// Create takes the representation of a vault and creates it.  Returns the server's representation of the vault, and an error, if there is any.
func (c *FakeVaults) Create(ctx context.Context, vault *v1alpha2.Vault, opts v1.CreateOptions) (result *v1alpha2.Vault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vaultsResource, c.ns, vault), &v1alpha2.Vault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Vault), err
}

// Update takes the representation of a vault and updates it. Returns the server's representation of the vault, and an error, if there is any.
func (c *FakeVaults) Update(ctx context.Context, vault *v1alpha2.Vault, opts v1.UpdateOptions) (result *v1alpha2.Vault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vaultsResource, c.ns, vault), &v1alpha2.Vault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Vault), err
}

// Delete takes name of the vault and deletes it. Returns an error if one occurs.
func (c *FakeVaults) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(vaultsResource, c.ns, name, opts), &v1alpha2.Vault{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVaults) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vaultsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.VaultList{})
	return err
}

// Patch applies the patch and returns the patched vault.
func (c *FakeVaults) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.Vault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vaultsResource, c.ns, name, pt, data, subresources...), &v1alpha2.Vault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Vault), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied vault.
func (c *FakeVaults) Apply(ctx context.Context, vault *vaultv1alpha2.VaultApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha2.Vault, err error) {
	if vault == nil {
		return nil, fmt.Errorf("vault provided to Apply must not be nil")
	}
	data, err := json.Marshal(vault)
	if err != nil {
		return nil, err
	}
	name := vault.Name
	if name == nil {
		return nil, fmt.Errorf("vault.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vaultsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha2.Vault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.Vault), err
}
