// Copyright © 2019 Banzai Cloud
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/bank-vaults/vault-operator/pkg/apis/vault/v1alpha1"
	vaultv1alpha1 "github.com/bank-vaults/vault-operator/pkg/client/clientset/versioned/typed/vault/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeVaults implements VaultInterface
type fakeVaults struct {
	*gentype.FakeClientWithList[*v1alpha1.Vault, *v1alpha1.VaultList]
	Fake *FakeVaultV1alpha1
}

func newFakeVaults(fake *FakeVaultV1alpha1, namespace string) vaultv1alpha1.VaultInterface {
	return &fakeVaults{
		gentype.NewFakeClientWithList[*v1alpha1.Vault, *v1alpha1.VaultList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("vaults"),
			v1alpha1.SchemeGroupVersion.WithKind("Vault"),
			func() *v1alpha1.Vault { return &v1alpha1.Vault{} },
			func() *v1alpha1.VaultList { return &v1alpha1.VaultList{} },
			func(dst, src *v1alpha1.VaultList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.VaultList) []*v1alpha1.Vault { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.VaultList, items []*v1alpha1.Vault) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
